openapi: 3.0.3
info:
  title: Api-сервер для проекта 6 городов
  version: 1.0.0
  description: API для проекта 6 городов
servers:
  - url: 'http://localhost:3000'
components:
  schemas:
    Offer:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        type:
          type: string
          enum: [apartment, house, room, hotel]
        isPremium:
          type: boolean
        isFavorite:
          type: boolean
        rating:
          type: number
          format: float
        createdAt:
          type: string
          format: date-time
        city:
          type: string
          enum: [Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf]
        previewImage:
          type: string
          format: uri
        images:
          type: array
          items:
            type: string
            format: uri
        goods:
          type: array
          items:
            type: string
        bedrooms:
          type: integer
        maxAdults:
          type: integer
        host:
          type: string
          format: objectid
          pattern: "^[a-fA-F0-9]{24}$"
        commentCount:
          type: integer
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
      required:
        - title
        - price
        - type
        - city
        - previewImage
        - bedrooms
        - maxAdults
        - host
        - isPremium
        - isFavorite
        - rating
        - createdAt
        - commentCount
        - latitude
        - longitude

    User:
      type: object
      properties:
        id:
          type: string
          format: objectid
        email:
          type: string
          format: email
        name:
          type: string
          minLength: 1
          maxLength: 15
        avatarUrl:
          type: string
          format: uri
          pattern: '\.(jpg|png)$'
        type:
          type: string
          enum: [usual, pro]
      required:
        - email
        - name
        - type

    Comment:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time
        user:
          $ref: "#/components/schemas/User"
      required:
        - content
        - createdAt
        - user

    CreateCommentDto:
      type: object
      properties:
        content:
          type: string
          minLength: 5
          maxLength: 1024
        rating:
          type: integer
          minimum: 1
          maximum: 5
        userId:
          type: string
          format: objectid
          pattern: "^[a-fA-F0-9]{24}$"
        offerId:
          type: string
          format: objectid
          pattern: "^[a-fA-F0-9]{24}$"
      required:
        - content
        - rating
        - userId
        - offerId

    CreateUserDto:
      type: object
      properties:
        email:
          type: string
          format: email
        name:
          type: string
          minLength: 1
          maxLength: 15
        password:
          type: string
          minLength: 6
          maxLength: 12
        type:
          type: string
          enum: [usual, pro]
        avatarUrl:
          type: string
          format: uri
          pattern: '\.(jpg|png)$'
      required:
        - email
        - name
        - password
        - type

paths:
  /offers:
    get:
      summary: "Список предложений"
      operationId: "listOffers"
      tags:
        - "Offer"
      parameters:
        - name: "limit"
          in: "query"
          description: "Количество предложений"
          required: false
          schema:
            type: integer
            default: 10
        - name: "sort"
          in: "query"
          description: "Сортировка предложений"
          required: false
          schema:
            type: string
            default: "createdAt_desc"
      responses:
        "200":
          description: "Список предложений"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Offer"

    post:
      summary: "Создание нового предложения"
      operationId: "createOffer"
      tags:
        - "Offer"
      security:
        - BearerAuth: []
      requestBody:
        description: "Данные для создания нового предложения"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Offer"
      responses:
        "201":
          description: "Предложение успешно создано"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offer"
        "400":
          description: "Ошибка валидации данных"
        "401":
          description: "Неавторизованный запрос"

    patch:
      summary: "Обновление предложения"
      operationId: "updateOffer"
      tags:
        - "Offer"
      security:
        - BearerAuth: []
      requestBody:
        description: "Данные для обновления предложения"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Offer"
      responses:
        "200":
          description: "Предложение успешно обновлено"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offer"
        "404":
          description: "Предложение не найдено"

  /offers/{offerId}:
    get:
      summary: "Детальная информация о предложении"
      operationId: "getOfferById"
      tags:
        - "Offer"
      parameters:
        - name: "offerId"
          in: "path"
          required: true
          schema:
            type: string
            format: objectid
            pattern: "^[a-fA-F0-9]{24}$"
      responses:
        "200":
          description: "Детальная информация о предложении"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offer"
        "404":
          description: "Предложение не найдено"

    delete:
      summary: "Удаление предложения"
      operationId: "deleteOffer"
      tags:
        - "Offer"
      security:
        - BearerAuth: []
      parameters:
        - name: "offerId"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "204":
          description: "Предложение успешно удалено"
        "404":
          description: "Предложение не найдено"

  /offers/premium:
    get:
      summary: "Премиальные предложения"
      operationId: "getPremiumOffers"
      tags:
        - "Offer"
      parameters:
        - name: "city"
          in: "query"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Список премиальных предложений"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Offer"

  /favorites:
    get:
      summary: "Список избранных предложений"
      operationId: "getFavoriteOffers"
      tags:
        - "Offer"
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "Список избранных предложений"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Offer"
  /favorites/{offerId}:
    post:
      summary: "Добавить предложение в избранное"
      operationId: "addOfferToFavorites"
      tags:
        - "Offer"
      security:
        - BearerAuth: []
      parameters:
        - name: "offerId"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Предложение добавлено в избранное"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offer"
        "401":
          description: "Неавторизованный запрос"
        "404":
          description: "Предложение не найдено"

    delete:
      summary: "Удалить предложение из избранного"
      operationId: "removeOfferFromFavorites"
      tags:
        - "Offer"
      security:
        - BearerAuth: []
      parameters:
        - name: "offerId"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Предложение удалено из избранного"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offer"
        "401":
          description: "Неавторизованный запрос"
        "404":
          description: "Предложение не найдено"
  /comments/{offerId}:
    get:
      summary: "Список комментариев для предложения"
      operationId: "listComments"
      tags:
        - "Comment"
      parameters:
        - name: "offerId"
          in: "path"
          description: "ID предложения"
          required: true
          schema:
            type: string
            format: objectid
            pattern: "^[a-fA-F0-9]{24}$"
        - name: "limit"
          in: "query"
          description: "Количество комментариев"
          required: false
          schema:
            type: integer
            default: 50
      responses:
        "200":
          description: "Список комментариев"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Comment"
  /comments:
    post:
      summary: "Добавление комментария"
      operationId: "createComment"
      tags:
        - "Comment"
      security:
        - BearerAuth: []
      requestBody:
        description: "Тело комментария"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCommentDto"
      responses:
        "201":
          description: "Комментарий успешно добавлен"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        "400":
          description: "Ошибка валидации данных"
        "401":
          description: "Неавторизованный запрос"
  /users/register:
    post:
      summary: "Создание нового пользователя"
      operationId: "createUser"
      tags:
        - "User"
      requestBody:
        description: "Данные для создания нового пользователя"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserDto"
      responses:
        "201":
          description: "Пользователь успешно создан"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: "Ошибка валидации данных"

  /users/avatar/{userId}:
    post:
      summary: "Загрузка аватара пользователя"
      operationId: "uploadUserAvatar"
      tags:
        - "User"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          schema:
            type: string
            format: objectid
            pattern: "^[a-fA-F0-9]{24}$"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
            encoding:
              avatar:
                contentType: image/png, image/jpeg, image/jpg
      responses:
        "201":
          description: "Аватар успешно загружен"
          content:
            application/json:
              schema:
                type: object
                properties:
                  avatarUrl:
                    type: string
                    format: uri
        "400":
          description: "Файл не загружен"
        "404":
          description: "Пользователь не найден"

  /auth/login:
    post:
      summary: "Вход в аккаунт"
      operationId: "login"
      tags:
        - "Auth"
      requestBody:
        description: "Данные для аутентификации"
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: "Успешная аутентификация"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: "Неверный логин или пароль"
  /auth/logout:
    post:
      summary: "Выход из аккаунта"
      operationId: "logout"
      tags:
        - "Auth"
      security:
        - BearerAuth: []
      responses:
        "204":
          description: "Сеанс завершен"
